#  type: ignore
"""init

Revision ID: 01ca2af0d8d2
Revises:
Create Date: 2022-06-08 13:45:12.928787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01ca2af0d8d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'csv_file',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('file_name', sa.String(), nullable=True),
        sa.Column('file_src', sa.String(), nullable=True),
        sa.Column(
            'columns', postgresql.ARRAY(sa.String(), dimensions=1), nullable=True
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_csv_file_created_at'), 'csv_file', ['created_at'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_csv_file_created_at'), table_name='csv_file')
    op.drop_table('csv_file')
    # ### end Alembic commands ###
