"""init2

Revision ID: 93dfbf328fcb
Revises: 01ca2af0d8d2
Create Date: 2022-06-08 14:46:22.085964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93dfbf328fcb'
down_revision = '01ca2af0d8d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csv_file', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csv_file', 'file_size')
    # ### end Alembic commands ###
